package com.example.pedro.prottipo1.dao;

import com.example.pedro.prottipo1.modelo.Tipos;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class TiposDAO {

    public List<Tipos> lista() {
        List<Tipos> pacotes = new ArrayList<>(Arrays.asList(
                new Tipos("@drawable/lesaoporpressao1", "Lesão por Pressão Estágio 1: Pele íntegra com eritema que não embranquece","Pele íntegra com área localizada de eritema que não embranquece e que pode parecer diferente em pele de cor escura. Presença de eritema que embranquece ou mudanças na sensibilidade, temperatura ou consistência (endurecimento) podem preceder as mudanças visuais. Mudanças na cor não incluem descoloração púrpura ou castanha; essas podem indicar dano tissular profundo."),
                new Tipos("@drawable/lesaoporpressao2", "Lesão por Pressão Estágio 2: Perda da pele em sua espessura parcial com exposição da derme","Perda da pele em sua espessura parcial com exposição da derme. O leito da ferida é viável, de coloração rosa ou vermelha, úmido e pode também apresentar-se como uma bolha intacta (preenchida com exsudato seroso) ou rompida. O tecido adiposo e tecidos profundos não são visíveis. Tecido de granulação, esfacelo e escara não estão presentes. Essas lesões geralmente resultam de microclima inadequado e cisalhamento da pele na região da pélvis e no calcâneo. Esse estágio não deve ser usado para descrever as lesões de pele associadas à umidade, incluindo a dermatite associada à incontinência (DAI), a dermatite intertriginosa, a lesão de pele associada a adesivos médicos ou as feridas traumáticas (lesões por fricção, queimaduras, abrasões)."),
                new Tipos("@drawable/lesaoporpressao3", "Lesão por Pressão Estágio 3: Perda da pele em sua espessura total","Perda da pele em sua espessura total na qual a gordura é visível e, frequentemente, tecido de granulação e epíbole (lesão com bordas enroladas) estão presentes. Esfacelo e /ou escara pode estar visível. A profundidade do dano tissular varia conforme a localização anatômica; áreas com adiposidade significativa podem desenvolver lesões profundas. Podem ocorrer descolamento e túneis. Não há exposição de fáscia, músculo, tendão, ligamento, cartilagem e/ou osso. Quando o esfacelo ou escara prejudica a identificação da extensão da perda tissular, deve-se classificá-la como Lesão por Pressão Não Classificável."),
                new Tipos("@drawable/lesaoporpressao4", "Lesão por pressão Estágio 4: Perda da pele em sua espessura total e perda tissular","Perda da pele em sua espessura total e perda tissular com exposição ou palpação direta da fáscia, músculo, tendão, ligamento, cartilagem ou osso. Esfacelo e /ou escara pode estar visível. Epíbole (lesão com bordas enroladas), descolamento e/ou túneis ocorrem frequentemente. A profundidade varia conforme a localização anatômica. Quando o esfacelo ou escara prejudica a identificação da extensão da perda tissular, deve-se classificá-la como Lesão por Pressão Não Classificável."),
                new Tipos("@drawable/lesaoporpressao5", "Lesão por Pressão Não Classificável: Perda da pele em sua espessura total e perda tissular não visível.","Perda da pele em sua espessura total e perda tissular na qual a extensão do dano não pode ser confirmada porque está encoberta pelo esfacelo ou escara. Ao ser removido (esfacelo ou escara), Lesão por Pressão em Estágio 3 ou Estágio 4 ficará aparente. Escara estável (isto é, seca, aderente, sem eritema ou flutuação) em membro isquêmico ou no calcâneo não deve ser removida."),
                new Tipos("@drawable/lesaoporpressao6", "Lesão por Pressão Tissular Profunda: descoloração vermelho escura, marrom ou púrpura, persistente e que não embranquece.","Pele intacta ou não, com área localizada e persistente de descoloração vermelha escura, marrom ou púrpura que não embranquece ou separação epidérmica que mostra lesão com leito escurecido ou bolha com exsudato sanguinolento. Dor e mudança na temperatura frequentemente precedem as alterações de coloração da pele. A descoloração pode apresentar-se diferente em pessoas com pele de tonalidade mais escura. Essa lesão resulta de pressão intensa e/ou prolongada e de cisalhamento na interface osso-músculo. A ferida pode evoluir rapidamente e revelar a extensão atual da lesão tissular ou resolver sem perda tissular. Quando tecido necrótico, tecido subcutâneo, tecido de granulação, fáscia, músculo ou outras estruturas subjacentes estão visíveis, isso indica lesão por pressão com perda total de tecido (Lesão por Pressão Não Classificável ou Estágio 3 ou Estágio 4). Não se deve utilizar a categoria Lesão por Pressão Tissular Profunda (LPTP) para descrever condições vasculares, traumáticas, neuropáticas ou dermatológicas.\n" +
                        "\n"),
                new Tipos("@color/preto", "Lesão por Pressão Relacionada a Dispositivo Médico","Essa terminologia descreve a etiologia da lesão. A Lesão por Pressão Relacionada a Dispositivo Médico resulta do uso de dispositivos criados e aplicados para fins diagnósticos e terapêuticos. A lesão por pressão resultante geralmente apresenta o padrão ou forma do dispositivo. Essa lesão deve ser categorizada usando o sistema de classificação de lesões por pressão."),
                new Tipos("@color/preto", "Lesão por Pressão em Membranas Mucosas","A lesão por pressão em membranas mucosas é encontrada quando há histórico de uso de dispositivos médicos no local do dano. Devido à anatomia do tecido, essas lesões não podem ser categorizadas.")));
        return pacotes;
    }

}
